[package]
name = "kenken"
version = "0.3.0"
edition = "2024"
description = "KenKen puzzle generator and solver"
license = "MIT"
repository = "https://github.com/wpm/KenKen"
keywords = ["kenken", "puzzle", "generator", "solver"]
categories = ["games"]
readme = "README.md"
exclude = [".githooks", ".github"]

[dependencies]
rand = "0.10.1"
strum = { version = "0.28", features = ["derive"] }


[dev-dependencies]
itertools = "0.14"
rand_chacha = "0.10.0"

[lints.rust]
unused_results = "warn"
