name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, llvm-tools

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@cargo-llvm-cov

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: |
          cargo clippy --all-targets --all-features -- \
            -D warnings \
            -D clippy::all \
            -D clippy::pedantic \
            -D clippy::nursery \
            -D clippy::unwrap_used \
            -D clippy::expect_used \
            -D clippy::panic \
            -D clippy::todo \
            -D clippy::unimplemented \
            -D clippy::dbg_macro \
            -D clippy::print_stdout \
            -D clippy::print_stderr

      - name: Test
        run: cargo llvm-cov --all-features --lcov --output-path lcov.info --fail-under-lines 99

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: wpm/KenKen
          files: lcov.info

      - name: Doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: -D warnings
